// Hand-picked common breeds for intake-form autocomplete.
// Sources: AKC (American Kennel Club) common-breed roster + CFA (Cat Fanciers'
// Association) and TICA (The International Cat Association) registries.
//
// Free-form text still allowed at intake time — this is a `<datalist>` for
// autocomplete, not a strict allowlist. The point is to keep typos out of the
// AI sprite-generation prompt for the 95% case where the breed is mainstream.
//
// Add to either list as needed.

export const DOG_BREEDS: ReadonlyArray<string> = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Eskimo Dog",
  "American Foxhound",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Anatolian Shepherd",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Australian Terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Bernedoodle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black Russian Terrier",
  "Bloodhound",
  "Bluetick Coonhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Briard",
  "Brittany",
  "Brussels Griffon",
  "Bulldog",
  "Bullmastiff",
  "Bull Terrier",
  "Cairn Terrier",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Catahoula Leopard Dog",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chow Chow",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie",
  "Coton de Tulear",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "English Setter",
  "English Springer Spaniel",
  "Field Spaniel",
  "Finnish Lapphund",
  "Flat-Coated Retriever",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd",
  "German Shorthaired Pointer",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greater Swiss Mountain Dog",
  "Greyhound",
  "Havanese",
  "Ibizan Hound",
  "Irish Setter",
  "Irish Terrier",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Keeshond",
  "Komondor",
  "Labradoodle",
  "Labrador Retriever",
  "Lhasa Apso",
  "Maltese",
  "Maltipoo",
  "Mastiff",
  "Miniature American Shepherd",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Mixed Breed",
  "Mountain Cur",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Papillon",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Petit Basset Griffon Vendeen",
  "Pharaoh Hound",
  "Plott Hound",
  "Pointer",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Puggle",
  "Puli",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Shar Pei",
  "Sheepadoodle",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Soft Coated Wheaten Terrier",
  "Spinone Italiano",
  "Staffordshire Bull Terrier",
  "Standard Poodle",
  "Standard Schnauzer",
  "Sussex Spaniel",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Poodle",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "West Highland White Terrier",
  "Whippet",
  "Wirehaired Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Yorkshire Terrier",
];

export const CAT_BREEDS: ReadonlyArray<string> = [
  "Abyssinian",
  "American Bobtail",
  "American Curl",
  "American Shorthair",
  "American Wirehair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Longhair",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Calico",
  "Chartreux",
  "Cornish Rex",
  "Devon Rex",
  "Domestic Longhair",
  "Domestic Mediumhair",
  "Domestic Shorthair",
  "Egyptian Mau",
  "European Shorthair",
  "Exotic Shorthair",
  "Havana Brown",
  "Himalayan",
  "Japanese Bobtail",
  "Khao Manee",
  "Korat",
  "LaPerm",
  "Maine Coon",
  "Manx",
  "Mixed Breed",
  "Munchkin",
  "Nebelung",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental Longhair",
  "Oriental Shorthair",
  "Persian",
  "Peterbald",
  "Pixie-Bob",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Somali",
  "Sphynx",
  "Tabby",
  "Tonkinese",
  "Tortoiseshell",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
];

// Combined list for the unified <datalist>. Native autocomplete filters by
// substring as the user types, so a single list works for both species —
// "Mai..." matches Maine Coon (cat) and "Mal..." matches Belgian Malinois
// (dog). We dedupe shared names like "Mixed Breed".
export const ALL_BREEDS: ReadonlyArray<string> = Array.from(
  new Set([...DOG_BREEDS, ...CAT_BREEDS])
).sort();
